### ISSUE TITLE
Error when importing posts from WordPress blogs

### ISSUE THREAD

**Issue by charitygamble** [11ty/eleventy-import#9]
Using npx @11ty/import wordpress [blog url] --output=public - I can import all of the assets, but as soon as it starts to import posts, it does the following:

Importing post public\blurring-the-lines-extras-by-amy-kaybach\.md (5.81kB) from https://www.charlisbookbox.com/blurring-the-lines-extras-by-amy-kaybach/
node:fs:2346
    return binding.writeFileUtf8(
                   ^

Error: ENOENT: no such file or directory, open 'C:\Users\demen\OneDrive\Desktop\CharityGambleDeveloper\bookbox\public\blurring-the-lines-extras-by-amy-kaybach\.md'
    at Object.writeFileSync (node:fs:2346:20)
    at Importer.toFiles (file:///C:/Users/demen/OneDrive/Desktop/CharityGambleDeveloper/bookbox/node_modules/@11ty/import/src/Importer.js:462:8)
    at file:///C:/Users/demen/OneDrive/Desktop/CharityGambleDeveloper/bookbox/node_modules/@11ty/import/cli.js:142:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\demen\\OneDrive\\Desktop\\CharityGambleDeveloper\\bookbox\\public\\blurring-the-lines-extras-by-amy-kaybach\\.md'
}

It does not matter if the public folder is already created or not and this issue happens consistently whether I am attempting to import from a self-hosted WordPress installation or from a WordPress.com blog - the first post that tries to import consistently fails to work because the markdown file doesn't exist. Any ideas why this is happening? I've tried multiple times and it just never imports the posts, only the assets (images). 

I'm not sure if this is a weird bug or possibly user-error, but it doesn't seem to matter how I do it or what WordPress source I use, it seems to always do this.

**Comment by TechLifeWeb** [comment]
I'm getting similar errors when I attempt to import an RSS feed. I'm testing on Windows, and it seems that if the folders that the files are supposed to be put into don't already exist then it throws the error. If I manually create folders, then run the import it works.
